Fix squeezed Toml Files
TheElectronWill/night-config pull request #154
Opened 2024-01-23 18:17 UTC by Stein-N

As described in discussion #153, ​​the TableEntries were squeezed together by the new check in the TableWriter.

The check separates the TablesEntries from the normal/simple written values inside the Toml File.

This simple Solution separates the TableEntries and TableArrayEntries from each other without effecting the Entry or List by itself.
Means the ArrayList gets further squeezed together but when a new ArrayList is written a blank line is written in between.

2024-01-26 17:49 UTC, TheElectronWill commented
Looks good to me, nice little contribution

2024-01-26 17:51 UTC, TheElectronWill commented
Do you want to try to add unit tests? Otherwise I can write them.

2024-01-26 18:03 UTC, Stein-N commented
> Do you want to try to add unit tests? Otherwise I can write them.

Never wrote testing to this point, would try tomorrow and will commit them. Hope they will be good 😁

2024-01-27 10:23 UTC, Stein-N commented
The second empty line at the end of the file can be "fixed" by modifying the writeNormal Function, by adding an counter for the Amount of TableEntries and TableArrayEntries and decreasing it everytime one Entrie/Array was written:

```java
private static void writeNormal(UnmodifiableCommentedConfig config, List<String> configPath,
									CharacterOutput output, TomlWriter writer) {
		List<UnmodifiableCommentedConfig.Entry> tablesEntries = new ArrayList<>();
		List<UnmodifiableCommentedConfig.Entry> tableArraysEntries = new ArrayList<>();

		int tableEntriesAmount = 0; // Fix for second empty line at the end of the File
		int tableArrayEntriesAmount = 0; // Fix for second empty line at the end of the File

		// Writes the "simple" values:
		writer.increaseIndentLevel();// Indent++
		for (UnmodifiableCommentedConfig.Entry entry : config.entrySet()) {
			final String key = entry.getKey();
			final Object value = entry.getValue();
			final String comment = entry.getComment();
			if (value instanceof UnmodifiableConfig &&
				!writer.writesInline((UnmodifiableConfig)value)) {
				tablesEntries.add(entry);
				tableEntriesAmount++;
				continue;
			} else if (value instanceof List) {
				List<?> list = (List<?>)value;
				if (!list.isEmpty() && list.stream().allMatch(UnmodifiableConfig.class::isInstance)) {
					tableArraysEntries.add(entry);
					tableArrayEntriesAmount++;
					continue;
				}
			}
			writer.writeComment(comment, output);// Writes the comment above the key
			writer.writeIndent(output);// Indents the line.
			writer.writeKey(key, output);
			output.write(KEY_VALUE_SEPARATOR);
			ValueWriter.write(value, output, writer);
			writer.writeNewline(output);
		}

		int nonSimpleValuesCount = tablesEntries.size() + tableArraysEntries.size();
		int simpleValuesCount = config.size() - nonSimpleValuesCount;
		if (simpleValuesCount > 0 && nonSimpleValuesCount > 0) {
			writer.writeNewline(output);
		}

		// Writes the tables:
		for (UnmodifiableCommentedConfig.Entry entry : tablesEntries) {
			// Writes the comment, if there is one
			writer.writeComment(entry.getComment(), output);

			// Writes the table declaration
			configPath.add(entry.getKey());// path level ++
			writeTableName(configPath, output, writer);
			writer.writeNewline(output);

			// Writes the table's content
			writeNormal(entry.<UnmodifiableConfig>getValue(), configPath, output, writer);
			configPath.remove(configPath.size() - 1);// path level --
			tableEntriesAmount--;// Fix for second empty line at the end of the File
                        if (tableEntriesAmount > 0) writer.writeNewline(output); // Fix for second empty line at the end of the File
		}

		// Writes the arrays of tables:
		for (UnmodifiableCommentedConfig.Entry entry : tableArraysEntries) {
			// Writes the comment, if there is one
			writer.writeComment(entry.getComment(), output);

			// Writes the tables
			configPath.add(entry.getKey());// path level ++
			List<Config> tableArray = entry.getValue();
			for (UnmodifiableConfig table : tableArray) {
				writeTableArrayName(configPath, output, writer);
				writer.writeNewline(output);
				writeNormal(table, configPath, output, writer);
			}
			configPath.remove(configPath.size() - 1);// path level --
			tableArrayEntriesAmount--;// Fix for second empty line at the end of the File
			if (tableArrayEntriesAmount > 0) writer.writeNewline(output); // Fix for second empty line at the end of the File
		}
		writer.decreaseIndentLevel();// Indent--
	}
```

But this seems unnecessary because this additional empty line only appears at the end of the toml file.
So i would say it is better only to add this empty line to the tests rather than adding this check.

2024-01-27 11:07 UTC, TheElectronWill requested changes
`java.sql.Array` should not be imported, other that that it's ok.

2024-01-27 11:07 UTC, TheElectronWill commented on toml/src/test/java/com/electronwill/nightconfig/toml/TomlWriterTest.java
> +import java.sql.Array;
spurious import :eyes:

2024-01-27 11:07 UTC, TheElectronWill commented on toml/src/test/java/com/electronwill/nightconfig/toml/TomlWriterTest.java
> +		assertLinesMatch(Arrays.asList("simple = 123", "", "[table]", "\tkey = \"value\"", "", ""),
this additional line is not ideal but that's good enough, we can figure out a better solution later

2024-01-27 11:15 UTC, Stein-N commented
changes made

2024-01-27 11:22 UTC, TheElectronWill approved these changes
Thanks!

2024-01-27 11:22 UTC, merged