Fix config map creators not inheriting for TOML and JSON
TheElectronWill/night-config pull request #86
Opened 2020-11-15 20:15 UTC by diesieben07

This causes child configs to not preserve iteration order, even though it has been set for their parent.
This fixes #85, at least for TOML and JSON. For Hocon it is not easily possible, because the underlying library Typesafe Config always uses a plain HashMap and this behavior is not configurable.

I've also added tests for TOML and JSON to test this behavior.

2020-11-18 08:58 UTC, TheElectronWill requested changes
Thanks for the PR!
As said in the review, it would be better to make `parentConfig` a `CommentedConfig` everywhere and use `CommentedConfig.fake` only at the beginning of the parsing and if necessary.

2020-11-19 09:06 UTC, diesieben07 commented on toml/src/main/java/com/electronwill/nightconfig/toml/TableParser.java
> +		CommentedConfig config = CommentedConfig.fake(parentConfig.createSubConfig());
I've moved the `fake` calls as "far up" in the chain as possible. The only place where it is used in `TomlParser` now is during the existing `instanceof Config` checks. That said, `fake` first checks if the config is already a `CommentedConfig` and if so just returns it immediately - so no comments should get lost if they _can_ be stored.

2020-11-19 10:14 UTC, TheElectronWill commented on toml/src/main/java/com/electronwill/nightconfig/toml/TableParser.java
> +		CommentedConfig config = CommentedConfig.fake(parentConfig.createSubConfig());
> That said, fake first checks if the config is already a CommentedConfig and if so just returns it immediately - so no comments should get lost if they can be stored.
Right! I have to thank my past self for that, I guess :smile:

2020-11-19 10:16 UTC, TheElectronWill commented
LGTM! thanks

2020-11-19 10:16 UTC, merged